---

driver:
  name: docker

platforms:
  - name: aws_vpc-localstack
    env:
      DEBUG: "1"
      SERVICES: cloudformation
    image: localstack/localstack:0.9.3
    exposed_ports:
      - 4581/tcp
    published_ports:
      - 0.0.0.0:4581:4581/tcp

provisioner:
  name: ansible
  env:
    AWS_ACCESS_KEY_ID: foobar
    AWS_DEFAULT_REGION: foobar
    AWS_SECRET_ACCESS_KEY: foobar
  lint:
    name: ansible-lint
  options:
    vvv: True

lint:
  name: yamllint
  options:
    config-data:
      extends: default
      ignore: .venv_ansible*
      rules:
        line-length:
          max: 159
        truthy: disable

dependency:
  name: galaxy

scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - destroy

verifier:
  name: testinfra
  lint:
    name: flake8
